=head1 GSL - GNU Scientific Library for Parrot VM

This GSL for Parrot is Copyright (C) by John W. Emerson
See F<LICENSE> for licensing details, Artistic License 2.0.

This is repository GSL in github organization NQRCore,
established July 10, 2011.  GSL is the GNU Scientific
Library for the Parrot Virtual Machine.

Jay Emerson (john.emerson@yale.edu or jayemerson@gmail.com)

=head2 Building from source

GSL requires Parrot (see http://www.parrot.org).  If you can
build Parrot, you should be fine building GSL.  You will also
need both libffi and libffi-dev.  The configuration/building
process is a work in progress (or not yet in progress).

To obtain GSL directly from its repository:

    $ git clone git://github.com/NQRCore/GSL.git

I don't expect anyone will use this directly, but will rather
link the functionality into their own projects via the native
call interface (NCI) of Parrot.
